### ISSUE TITLE
Music for ceremony

### ISSUE THREAD

**Issue by tamarum** [griswaldbrooks/wedding#223]
- [x] Choose song 
- [x] Find sheet notes for "Reflecting light" by Sam Phillips for cello/violin
- [x] Talk about it with the musicians

**Comment by griswaldbrooks** [comment]
Vase of flowers, tchaikovsy 1

Blue Danue, Strauss, 0.5
Father/daughter dance

===
Cardinal of Venice, Paganini, 1.2
Recessional 

Humoresque, Anthony dvorjka, 1.4, bridesmaid/groomsmen processional

Moon river, 1.6
Bride walk
