### ISSUE TITLE
Make hydrangea earrings

### ISSUE THREAD

**Issue by griswaldbrooks** [griswaldbrooks/wedding#86]
Making not buying. 
- [x] Buy dried hydrangea blossoms
- [x] Buy teardrop jewelry supplies.
- [x] Make non-resin prototype.
- [x] Resin the dried petals (?)
- [x] Do resin petal test
- [ ] Produce earrings (w/ or w/o resin), copy the Fleursenbiju earring design.

**Comment by tamarum** [comment]
- [] Find out what color to pick (bleu pale or bleu ciel) from [Fleursenbiju ](https://www.etsy.com/listing/867572811/earrings-in-real-hydrangea-flowers?click_key=67dc4fea11b7b91ebe519beb3fef4ddd1201f961%3A867572811&click_sum=c9994d14&ref=shop_home_active_2&frs=1&crt=1&variation0=1521121706&variation1=2195688746)

**Comment by tamarum** [comment]
Making not buying. 
- [ ] Buy dried hydrangea blossoms
- [ ] Buy teardrop jewelry supplies.
- [ ] Make non-resin prototype.
- [ ] Resin the dried petals (?)
- [ ] Produce earrings (w/ or w/o resin), copy the Fleursenbiju earring design.

**Comment by griswaldbrooks** [comment]
Hydrangeas ordered. Waiting on arrival. Expected arrival mid-late May

**Comment by griswaldbrooks** [comment]
Clear coat test started
