### ISSUE TITLE
Buy pajamas for bridal party and moms

### ISSUE THREAD

**Issue by griswaldbrooks** [griswaldbrooks/wedding#91]

**Comment by tamarum** [comment]
- See pjs on [amazon](https://www.amazon.com/dp/B08MQF15BM/?coliid=I3LMVN3XZN8VYF&colid=2703D24XI2LZG&psc=0&ref_=lv_ov_lig_dp_it)
- Need people's sizes

**Comment by tamarum** [comment]
- Sizes known;
Elaine - M
Ekaterina - XS/S

**Comment by griswaldbrooks** [comment]
Judy - L top M bottom

**Comment by tamarum** [comment]
Zi: S
Mari: Top S, Bottom M
Rena: top XS, Bottom S
